UPDATE jk_fields SET
ID_REPORT = 4,
POSICAO = 4,
FIELD_TITLE = 'TOTAL',
FIELD_NAME = 'total',
FIELD_TYPE = 'VALOR',
ORDENAR = null,
AGRUPAR = 'N',
TOTALIZAR = 'N',
FILTRO = null,
FILTRO_CONTEUDO = null,
TAMANHO = 2,
FIELD = 'vendas.total',
FIELD_FILTRO = 'N'
WHERE id_field = 82
